### ISSUE TITLE
Kitematic only showing 10 private repositories despite many more in organization

### ISSUE THREAD

**Issue by ultimateboy** [kitematic/kitematic#1158]
Using the latest release of kitematic, I'm only able to see 10 private repositories despite the fact that the organization I'm a member of has many more.

Steps to reproduce:
1. Log in to kitematic using a docker hub account that is a part of an organization with more than 10 private repositories
2. Click "My Repos"
3. Observe that only 10 repos show up

**Comment by FrenchBen** [comment]
@ultimateboy We implemented a fix for this which should be out here soon - Be on the lookout for a newer Docker Toolbox version

**Comment by ultimateboy** [comment]
@FrenchBen I'm still seeing this issue using the kitematic release that came out yesterday.

**Comment by FrenchBen** [comment]
@ultimateboy Thanks for the feedback - I'll check the code to see why more images aren't showing

**Comment by FrenchBen** [comment]
Fixed with https://github.com/kitematic/kitematic/pull/1180
