### ISSUE TITLE
Kitematic shows non-existing containers

### ISSUE THREAD

**Issue by schmunk42** [kitematic/kitematic#147]
I played around a lot with Docker in the past weeks and had 100s of stopped containers. I removed them but Kitematic (0.4.3) still shows some of them. I also tried to remove the folders from my Kitematic folder, but without luck (see attached screenshot)

![bildschirmfoto 2014-12-27 um 00 39 36](https://cloud.githubusercontent.com/assets/649031/5559894/1d0431ec-8d61-11e4-8635-06755f59781c.png)

**Comment by jeffdm** [comment]
Fixed in 0.5

**Comment by southwolf** [comment]
The problem still exists in 0.5.10. When I ran prom/prometheus  manually from docker CLI. When I ran it in Kitematic GUI, the container failed, so I had to run `docker run -p 9090:9090 prom/prometheus` manually, and lots of new containers jumped out. 
![screen shot 2015-03-30 at 9 58 16 am](https://cloud.githubusercontent.com/assets/150648/6889174/5afdb06c-d6c3-11e4-9a91-4a52ea3f294d.png)

**Comment by AndrewGorman** [comment]
This is still an issue with the most recent release. (0.17.8)

**Comment by vadimkuragkovskiy** [comment]
I have the same issue too on my mac. I feel that there is some issue in my configuration, but unfortunately I can't find any solution quite long time. 

Kitematic (or Dockstation) simply hangs with such huge list of containers or works pretty slowly. 

Perhaps someone could put here some advise in which direction I have to look to solve this?
