### ISSUE TITLE
node and meanjs repos did not start

### ISSUE THREAD

**Issue by ronnieserr** [kitematic/kitematic#611]
I tried the node official repo as well as the meanjs repo -- neither started at all.

The hello-world-nginx works well!

Please advise.

**Comment by TeckniX** [comment]
What's the log output for both of these failed containers?

**Comment by ronnieserr** [comment]
Hi,

In both cases, the log says "No logs for this container.”

The status line just next to the container name flashes “Running” for a split second, and then changes to “Stopped”.

I’m running Mac 10.10.3.

Ronnie

**Comment by TeckniX** [comment]
@ronnieserr Can you open the Docker CLI and run:
`docker ps -a`
find the `container id` of the meanjs container then:
`docker start <container_id>`

Then paste the message from the command-line here.

**Comment by mchiang0610** [comment]
@ronnieserr Hi Ronnie, sorry about this problem. 

The reason why the repos are not running is because those containers require specific commands to be inputted in order to run. 

(See: https://registry.hub.docker.com/_/node/  ) 

You can run these containers by using command line through the Docker CLI button.

**Comment by mchiang0610** [comment]
This is definitely a problem we need to solve on the Kitematic end though. (Perhaps by inserting a default run command to keep the containers running at least). 
@jeffdm @Elesant @nathanleclaire thoughts?

**Comment by ronnieserr** [comment]
Loki,

bash-3.2$ docker ps -a
CONTAINER ID        IMAGE                                COMMAND             CREATED             STATUS                         PORTS                   NAMES
9ce21bdc8834        maccam912/meanjs:latest              "/bin/bash"         3 hours ago         Exited (0) 2 minutes ago                               meanjs              
3a466458b0a2        node:latest                          "node"              3 hours ago         Exited (0) About an hour ago                           node                
590fad7910d7        kitematic/hello-world-nginx:latest   "sh /start.sh"      4 hours ago         Up 44 seconds                  0.0.0.0:32768->80/tcp   hello-world-nginx   
bash-3.2$ docker start 3a466458b0a2
3a466458b0a2
bash-3.2$ docker port hello-world-nginx
80/tcp -> 0.0.0.0:32768
bash-3.2$ docker port node
bash-3.2$ docker port meanjs

Also, I got a response from Michael Chiang

@ronnieserr <https://github.com/ronnieserr> Hi Ronnie, sorry about this problem. 

The reason why the repos are not running is because those containers require specific commands to be inputted in order to run. 

(See: https://registry.hub.docker.com/_/node/ <https://registry.hub.docker.com/_/node/> ) 

You can run these containers by using command line through the Docker CLI button.

And another

This is definitely a problem we need to solve on the Kitematic end though. (Perhaps by inserting a default run command to keep the containers running at least). 
@jeffdm <https://github.com/jeffdm> @Elesant <https://github.com/Elesant> @nathanleclaire <https://github.com/nathanleclaire> thoughts?

—————————

Also, can I run a Docker file from Kitematic?

Thanks,

Ronnie Serr
Alphabet House, Inc.
1725 S. Genesee Avenue
Los Angeles, CA 90019

323 939 1669 phone
ronnie@alphabethouse.com

**Comment by TeckniX** [comment]
@mchiang0610 - Perhaps read the CMD directive and display it in Kitematic? if none exist, add `/bin/ls` ?
I'm not sure of the best command to run which would also be always available?

**Comment by mchiang0610** [comment]
@TeckniX Yeah, that might work, but I don't think all CMDs will work correctly. 

For example, docker run node   (which pulls the official node image that has the CMD directive -  `CMD [ "node" ]` will not work.

**Comment by mchiang0610** [comment]
This is fixed with @TeckniX's latest pull request that has been merged. @ronnieserr can you try this again? 

Thanks!

**Comment by ronnieserr** [comment]
It's still not working

bash-3.2$ docker ps -a
CONTAINER ID        IMAGE                                COMMAND             CREATED             STATUS                      PORTS                   NAMES
cfc897a57f69        node:latest                          "node"              28 seconds ago      Exited (0) 21 seconds ago                           node                
590fad7910d7        kitematic/hello-world-nginx:latest   "sh /start.sh"      8 days ago          Up About a minute           0.0.0.0:32768->80/tcp   hello-world-nginx   
bash-3.2$

**Comment by TeckniX** [comment]
@ronnieserr Make sure to look in under the 'Advanced' tab setting and check both 'checkboxes' as follow:
![node](https://cloud.githubusercontent.com/assets/33699/8258918/c79f69ec-1686-11e5-8e34-b78caa78faee.png)

**Comment by ronnieserr** [comment]
Loki,

I'm using Kitematic 0.6.6 on Mac OS 10.10.3. There is no Advance tab under Settings. Also there's no horizontal nav bar ("General | Ports | ... ) under Settings. Please advise.

**Comment by TeckniX** [comment]
@ronnieserr If you look under the release tab: https://github.com/kitematic/kitematic/releases - A newer release 0.6.7 was just recently added. 
That version has the latest patch with the 'Advanced' tab.

**Comment by ronnieserr** [comment]
Yes, under 0.6.7 the container opens, thank you. But it does not configure the port

CONTAINER ID        IMAGE                                COMMAND             CREATED              STATUS              PORTS                   NAMES
64d262fd83a1        node:latest                          "node"              About a minute ago   Up About a minute                           node                
590fad7910d7        kitematic/hello-world-nginx:latest   "sh /start.sh"      9 days ago           Up 55 seconds       0.0.0.0:32768->80/tcp   hello-world-nginx

**Comment by TeckniX** [comment]
@ronnieserr if you look at the documentation, the following is explained:
`The image assumes that your application has a file named package.json listing its dependencies and defining its start script.`

The image you've selected may not be meant to run as you have it imagined. Read the full documentation:
https://registry.hub.docker.com/_/node/
